[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_add= '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = '''
let g:vimshell_vimshrc_path = expand('$HOME/.config/nvim/.vimshrc')
let g:vimshell_prompt = "vimshell% "
let g:vimshell_user_prompt = 'getcwd()'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
